name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

env:
  RUSTFLAGS: -Dwarnings
  CARGO_INCREMENTAL: 0 # Speeds up the build (no cache) and reduces disk space!

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Running rustfmt
      run: make rustfmt

  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Running clippy
      run: make check

  test:
    runs-on: ${{ fromJSON(github.repository == 'recallnet/builtin-actors' && '["self-hosted", "linux", "x64", "4xlarge"]' || '"ubuntu-latest"') }}
    steps:
    - name: Checking out
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - if: env.RUNNER_ENVIRONMENT != 'github-hosted'
      uses: dtolnay/rust-toolchain@stable
    - name: Running tests
      run: |
        cargo test --locked --all --no-fail-fast --exclude=recall_fil_builtin_actors_bundle

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: [ 'mainnet', 'caterpillarnet', 'butterflynet', 'calibrationnet', 'devnet', 'testing', 'testing-fake-proofs' ]
    steps:
    - name: Checking out
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Writing bundle
      env:
        BUILD_FIL_NETWORK: ${{ matrix.network }}
      run: |
        cargo run --locked -- -o output/builtin-actors.car
